### ISSUE TITLE
proxy key in source code

### ISSUE THREAD

**Issue by pim97** [azisfromchina/hcaptcha-solver#3]
[                //proxy: 'http://user-sp08f56c8e:sp08f56c8e@state.smartproxy.com:15000',](https://github.com/azisfromchina/hcaptcha-solver/blob/c4016b8a51d7db0dc4b96c055d850fa99ee1dd2a/src/Solver.js#LL36C53-L36C53)

just letting you know

**Comment by azisfromchina** [comment]
thanks, but its very old so its not a problem :)
